# Generated by Django 5.2.5 on 2025-08-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=25, verbose_name='工作時長(分鐘)')),
                ('break_duration', models.IntegerField(default=5, verbose_name='休息時長(分鐘)')),
                ('long_break_duration', models.IntegerField(default=15, verbose_name='長休息時長(分鐘)')),
                ('sessions_before_long_break', models.IntegerField(default=4, verbose_name='長休息前工作時段數')),
            ],
            options={
                'verbose_name': '番茄鐘設定',
                'verbose_name_plural': '番茄鐘設定',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '待辦事項',
                'verbose_name_plural': '待辦事項',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('work', '工作'), ('break', '休息')], max_length=5, verbose_name='時段類型')),
                ('duration', models.IntegerField(verbose_name='時長(分鐘)')),
                ('actual_duration', models.IntegerField(default=0, verbose_name='實際時長(分鐘)')),
                ('started_at', models.DateTimeField(verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='todo.todo', verbose_name='待辦事項')),
            ],
            options={
                'verbose_name': '番茄鐘時段',
                'verbose_name_plural': '番茄鐘時段',
                'ordering': ['-started_at'],
            },
        ),
    ]
