# Generated by Django 5.2.5 on 2025-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='actual_duration',
            field=models.FloatField(default=0.0, verbose_name='實際時長(分鐘)'),
        ),
    ]
